Handle different units in results.
redhat-performance/fio-wrapper pull request #28
Opened 2024-11-07 20:04 UTC by dvalinrh

Handle different units in results
Output csv file with individual process results.

2024-11-19 18:51 UTC, kdvalin requested changes

2024-11-19 18:51 UTC, kdvalin commented on fio/fio_run
> +}
As stated in pyperf wrapper, why duplicate the unit conversion across multiple wrappers?

2024-11-19 18:51 UTC, kdvalin commented on fio/fio_run
> +		base=`echo 1024*1024*1024 |bc`
Maybe to make this more readable, you can express KiB/s as 2^10, MiB/s as 2^20, etc.

2024-11-19 18:51 UTC, kdvalin commented on fio/fio_run
> +		base=1
Similar here for readability.

2024-12-12 18:39 UTC, kdvalin commented
Do we still need this after #35 ?

2024-12-12 18:51 UTC, malucius-rh commented
> Do we still need this after #35 ?

I don't think so, since #35 deals with it by using and handling the json output to get around fio's own foibles. This one sort of got superseded by the duplication-avoiding Zathras-core level work.

2025-01-21 19:09 UTC, dvalinrh commented
Will be fixed another way.

2025-01-21 19:09 UTC, closed without merging